apiVersion: v1
kind: Service
metadata:
  name: batching-inference-server
  labels:
    app: batching-inference-server
spec:
  selector:
    app: batching-inference-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
